<#ftl attributes={"description":"Warning with mailbox rule maintainer's contact information"}>
<#escape x as x?html>
    <p style="font-size: 12px; color: gray">
        ----<br/>
        <@l10n>
            This message was automatically generated by YouTrack.<br/>
            If you believe this message was sent to you by mistake, please contact our administrators: ${ruleMaintainer.email}<br/>
            For more information on YouTrack, visit its official website:
            <a href="http://www.jetbrains.com/youtrack">http://www.jetbrains.com/youtrack</a>
        </@l10n>
    </p>
</#escape>